language: c

env:
  global:
   # - LIBUV_PREFIX=$HOME/prebuilt/libuv-1.11.0 ;
   # - LIBUV_VERSION=1.11.0
   # - CMAKE_PREFIX=$HOME/prebuilt/cmake ;
   # - CMAKE_LINUX_URL=https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.sh ;
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: USE_CC=gcc USE_CXX=gcc CMAKE_BIN=$CMAKE_PREFIX/bin/cmake
    - os: linux
      dist: trusty
      sudo: required
      env: USE_CC=gcc-4.9 USE_CXX=gcc-4.9 CMAKE_BIN=$CMAKE_PREFIX/bin/cmake
    - os: linux
      dist: trusty
      sudo: required
      env: USE_CC=gcc-6 USE_CXX=gcc-6 CMAKE_BIN=$CMAKE_PREFIX/bin/cmake
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
      #   key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

    packages:
      - gcc-4.4
      - gcc-4.4-multilib
      - gcc-4.9
      - gcc-4.9-multilib
      - gcc-6
      - gcc-6-multilib

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
install:
    #- if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
    #      if [ ! -e "$CMAKE_BIN" ]; then
    #        mkdir -p "$CMAKE_PREFIX";
    #        curl --insecure -L "$CMAKE_LINUX_URL" -o cmake-linux.sh ;
    #        bash cmake-linux.sh --skip-license --prefix=$CMAKE_PREFIX ;
    #      fi
    #  fi
    wget "https://github.com/libuv/libuv/archive/v1.18.0.tar.gz"
    tar -xvf v1.18.0.tar.gz
    cd libuv-1.18.0
    sh autogen.sh
    ./configure
    make -j4
    sudo make install
    sudo ldconfig

# before_script:
#   - REPO_DIR=$PWD;
#   - cd /tmp
#   - if [ ! -e "$LIBUV_PREFIX/include/uv.h" ] || [ ! -e "$LIBUV_PREFIX/lib/libuv.so" ] ; then
#         if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
#           mkdir -p "$LIBUV_PREFIX";
#           wget -c "http://dist.libuv.org/dist/v$LIBUV_VERSION/libuv-v$LIBUV_VERSION.tar.gz" -O libuv-v$LIBUV_VERSION.tar.gz;
#           tar -xvf libuv-v$LIBUV_VERSION.tar.gz;
#           cd libuv-v$LIBUV_VERSION ;
#           ./autogen.sh;
#           ./configure --prefix=$LIBUV_PREFIX --with-pic=yes --enable-shared=yes --enable-static=no;
#           make -j4 install -Wl ;
#           cd -;
#           rm -rf libuv-v$LIBUV_VERSION libuv-v$LIBUV_VERSION ;
#         fi
#     fi
#   - cd "$REPO_DIR";

script: CC=$ENV_CC make all && CC=$ENV_CC make libuv && CC=$ENV_CC make libuv2
