language: c

env:
  global:
    # - LIBUV_PREFIX=$HOME/prebuilt/libuv-1.22.0 ;
    # - LIBUV_VERSION=1.22.0
    # - CMAKE_PREFIX=$HOME/prebuilt/cmake ;
    # - CMAKE_LINUX_URL=https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.sh ;
matrix:
  include:
    - os: linux
      dist: cosmic
      sudo: required
      env: USE_CC=gcc USE_CXX=g++ 
    # - os: linux
    #   dist: cosmic
    #   sudo: required
    #   env: USE_CC=gcc-4.9 USE_CXX=g++-4.9
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - gcc-4.9
    #         - gcc-4.9-multilib
    #         - g++-4.9
    #         - g++-4.9-multilib

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi

install:
    - sudo apt-get install libuv1;
    - sudo apt-get install libuv1-dev;


script: CC=$USE_CC make all
